//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypprojectapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENT
    {
        public int rentid { get; set; }
        public Nullable<int> renterid { get; set; }
        public Nullable<int> dressid { get; set; }
        public string rent_start_date { get; set; }
        public string rent_end_date { get; set; }
        public string status { get; set; }
        public string requeststatus { get; set; }
    
        public virtual DRESSINFO DRESSINFO { get; set; }
        public virtual USERINFO USERINFO { get; set; }
    }
}
