//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fypprojectapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHISHLIST
    {
        public int wislist_id { get; set; }
        public Nullable<int> requesterid { get; set; }
        public Nullable<int> dressid { get; set; }
        public string dress_status { get; set; }
        public string availabilty_date { get; set; }
    
        public virtual DRESSINFO DRESSINFO { get; set; }
        public virtual USERINFO USERINFO { get; set; }
    }
}
